SELECT * 
  FROM (
WITH ERROS --Para passar uma Ãºnica vez
  AS (
       SELECT E.MATERRO MATRICULA
           , COUNT(DISTINCT E.NUMOS) QT_OS_COM_ERRO
           , SUM(NVL(E.QT,0)) QT_DE_ERRO
        FROM PCWMSERRO E
           , PCEMPR EM
       WHERE  E.MATERRO = EM.MATRICULA
   
       AND E.NUMOS IN (SELECT M.NUMOS FROM PCMOVENDPEND M WHERE M.DTINICIOOS BETWEEN to_date('1','dd/MM/yyyy HH24:mi:ss') AND to_date('1','dd/MM/yyyy HH24:mi:ss') AND M.DTINICIOOS IS NOT NULL AND M.CODOPER NOT IN ('SA','EA')
       AND M.DTFIMSEPARACAO IS NOT NULL AND M.CODFUNCOS = EM.MATRICULA AND M.POSICAO = 'C' AND M.NUMOS IS NOT NULL)

       AND E.MATERRO = EM.MATRICULA
       group
          BY E.MATERRO   
      )
      
   , PRODUTIVIDADE
   AS (SELECT TAB.MATRICULA
           , WMS_FORMATATEMPODIA(SUM(TAB.TEMPO)) AS TEMPO
        FROM (select (MAX(dtfimseparacao)- MIN(dtinicioos)) tempo
                   , NUMOS
                   , CODFUNCOS MATRICULA
                from pcmovendpend
               where DTINICIOOS BETWEEN to_date('1','dd/MM/yyyy HH24:mi:ss') AND to_date('1','dd/MM/yyyy HH24:mi:ss')
                 AND CODFUNCOS IS NOT NULL
               GROUP 
                  BY NUMOS
                   , CODFUNCOS
             ) TAB
       GROUP
          BY TAB.MATRICULA
       )       
      
SELECT 'SEPARADOR' TIPO,
       PCEMPR.CODIGOPERFIL,
       PCEMPR.MATRICULA,    
       PCPERFILUSUARIOWMS.DESCRICAOPERFIL,                
       PCMOVENDPEND.CODFUNCOS FUNCIONARIO,
       PCEMPR.NOME,                  
       COUNT(DISTINCT TO_CHAR(PCMOVENDPEND.NUMOS,'FM0000000000') || TO_CHAR(PCMOVENDPEND.CODENDERECO,'FM0000000000')||PCMOVENDPEND.TIPOOS) QT_APANHA,
       TRUNC(SUM(PCMOVENDPEND.QT / DECODE(PCPRODUT.QTUNITCX,0,1,PCPRODUT.QTUNITCX))) QTCX,
       (SUM(PCMOVENDPEND.QT / DECODE(PCPRODUT.QTUNITCX,0,1,PCPRODUT.QTUNITCX))) - TRUNC(SUM(PCMOVENDPEND.QT / DECODE(PCPRODUT.QTUNITCX,0,1,PCPRODUT.QTUNITCX))) QTUND,       
       COUNT(DISTINCT PCMOVENDPEND.NUMOS) QUANT,
       COUNT(PCMOVENDPEND.CODPROD) + MAX((SELECT COUNT(*) FROM PCCORTEI I WHERE I. NUMPED=PCMOVENDPEND.NUMPED)) NUMAPANHA,
       SUM(PCMOVENDPEND.QT)QTR,
       ROUND(SUM(PCMOVENDPEND.QT * PCPRODUT.VOLUME), 4) VOLUME,
       SUM(PCMOVENDPEND.QT * PCPRODUT.PESOBRUTO) PESOBRUTO,
       (SUM(PCMOVENDPEND.QT)/COUNT(DISTINCT PCMOVENDPEND.NUMOS)) MQUANTPROD,
       (SUM(PCMOVENDPEND.QT * PCPRODUT.VOLUME)/COUNT(DISTINCT PCMOVENDPEND.NUMOS))MVOLUME,
       (SUM(PCMOVENDPEND.QT * PCPRODUT.PESOBRUTO)/COUNT(DISTINCT PCMOVENDPEND.NUMOS))MPESOBRUTO,                  
       COUNT(PCMOVENDPEND.CODPROD) TOTAPANHAS,          
   
       --max(ERROS.QT_OS_COM_ERRO) QT_OS_COM_ERRO,
       --max(ERROS.QT_DE_ERRO) QT_DE_ERRO,
       --max(PRODUTIVIDADE.TEMPO) TEMPO_CALC  
       
       (SELECT MAX(QT_OS_COM_ERRO) FROM ERROS WHERE MATRICULA = PCEMPR.MATRICULA) QT_OS_COM_ERRO,
       (SELECT MAX(QT_DE_ERRO) FROM ERROS WHERE MATRICULA = PCEMPR.MATRICULA) QT_DE_ERRO,
       (SELECT MAX(TEMPO) FROM PRODUTIVIDADE WHERE MATRICULA = PCEMPR.MATRICULA) TEMPO_CALC 
       
       
/*        (SELECT COUNT(DISTINCT M.NUMOS) FROM PCWMSERRO E, PCMOVENDPEND M, PCEMPR EM WHERE
       M.NUMOS=E.NUMOS
       AND E.MATERRO = EM.MATRICULA
       AND M.CODOPER NOT IN ('SA','EA')
       AND M.DTINICIOOS IS NOT NULL
       AND M.DTFIMSEPARACAO IS NOT NULL
       AND M.DTESTORNO IS NULL
       AND M.CODOPER NOT IN ('SA','EA')
       AND M.DTINICIOOS BETWEEN to_date('1','dd/MM/yyyy HH24:mi:ss') AND to_date('1','dd/MM/yyyy HH24:mi:ss')
       AND M.NUMOS IS NOT NULL
       and em.matricula = PCEMPR.MATRICULA
       --AND M.TIPOOS IN (SELECT CODTIPOOS FROM PCAUTORIOS WHERE CODIGOPERFIL = 21)
       ---ErrOS
       AND M.POSICAO in('C','A')) QT_OS_COM_ERRO,
        
       nvl((SELECT SUM(NVL(E.QT,0)) FROM PCWMSERRO E WHERE E.NUMOS IN (
       SELECT DISTINCT M.NUMOS FROM PCMOVENDPEND M, PCEMPR EM WHERE
       M.NUMOS=E.NUMOS
       AND E.MATERRO = EM.MATRICULA
       AND M.CODOPER NOT IN ('SA','EA')
       AND M.DTINICIOOS IS NOT NULL
       AND M.DTFIMSEPARACAO IS NOT NULL
       -- AND M.DTESTORNO IS NULL
       AND M.CODOPER NOT IN ('SA','EA')
       --AND M.DTINICIOOS BETWEEN  '2'  AND '2'
       AND M.DTINICIOOS BETWEEN to_date('1','dd/MM/yyyy HH24:mi:ss') AND to_date('1','dd/MM/yyyy HH24:mi:ss')
       AND M.NUMOS IS NOT NULL
        --AND M.TIPOOS IN (SELECT CODTIPOOS FROM PCAUTORIOS WHERE CODIGOPERFIL = 21)
       ---ErrOS
       and em.matricula = PCEMPR.MATRICULA
       AND M.POSICAO  in('C','A') )),0) QT_DE_ERRO,  */
       --WMS_FORMATATEMPODIA(SUM(DTINICIOOS-DTFIMSEPARACAO)) TEMPO_CALC   
       ---SEPARADOR
        --(WMS_OBTERTEMPO('1', '1', PCEMPR.MATRICULA, 'S', 0)) AS TEMPO_CALC
      -- (SELECT WMS_FORMATATEMPODIA(SUM(TAB.TEMPO)) AS TEMPO
           --  FROM (select (MIN(dtinicioos) - MAX(DTFIMSEPARACAO)) tempo,
                       --   NUMOS, CODFUNCCOFERENTE, CODFUNCCONF
                    -- from pcmovendpend
                  -- where DTINICIOOS BETWEEN to_date('1','dd/MM/yyyy HH24:mi:ss') AND to_date('1','dd/MM/yyyy HH24:mi:ss')
                   --where DATA = TRUNC(SYSDATE)
                     -- and nvl(CODFUNCCOFERENTE, CODFUNCCONF) = 1
                  --  GROUP BY NUMOS, CODFUNCCOFERENTE, CODFUNCCONF) TAB WHERE NVL(CODFUNCCOFERENTE, CODFUNCCONF) = PCEMPR.MATRICULA
                    
                  --  ) AS TEMPO_CALC 
                    
   -----CALCULAR TEMPO - SEPARADOR
    /*  (SELECT WMS_FORMATATEMPODIA(SUM(TAB.TEMPO)) AS TEMPO
             FROM (select (MAX(DTFIMSEPARACAO)-MIN(dtinicioos)) tempo,
                          NUMOS, NVL(CODFUNCOS,CODFUNCCOFERENTE) CODFUNCOS
                     from pcmovendpend
                   where DTINICIOOS BETWEEN to_date('1','dd/MM/yyyy HH24:mi:ss') AND to_date('1','dd/MM/yyyy HH24:mi:ss')
                    GROUP BY NUMOS, NVL(CODFUNCOS,CODFUNCCOFERENTE)) TAB WHERE CODFUNCOS = PCEMPR.MATRICULA)  
        AS TEMPO_CALC*/
       -----CALCULAR TEMPO     
                      
  FROM PCPRODUT,
       PCMOVENDPEND, 
       PCEMPR,
       PCPERFILUSUARIOWMS--,
       /*ERROS,
       PRODUTIVIDADE,
       PCPEDI,
       PCWMSERRO*/    
 WHERE PCPRODUT.CODPROD = PCMOVENDPEND.CODPROD
   AND PCEMPR.MATRICULA = PCMOVENDPEND.CODFUNCOS
   AND PCEMPR.CODIGOPERFIL = PCPERFILUSUARIOWMS.CODIGOPERFIL  
   AND PCMOVENDPEND.CODFILIAL = '1' 
   AND PCMOVENDPEND.DTFIMSEPARACAO IS NOT NULL
   AND PCMOVENDPEND.DTINICIOOS IS NOT NULL
   AND PCMOVENDPEND.CODOPER NOT IN ('SA','EA')
   --AND PCMOVENDPEND.DTINICIOOS BETWEEN to_date('1','dd/MM/yyyy HH24:mi:ss') AND to_date('1','dd/MM/yyyy HH24:mi:ss')
   and PCMOVENDPEND.DTINICIOOS >= to_date('1','dd/MM/yyyy HH24:mi:ss')
   and PCMOVENDPEND.DTINICIOOS <= to_date('1','dd/MM/yyyy HH24:mi:ss')
   AND PCMOVENDPEND.NUMOS IS NOT NULL
   AND PCMOVENDPEND.POSICAO = 'C'
   AND PCMOVENDPEND.DTFIMOS IS NOT NULL
   AND PCMOVENDPEND.DTESTORNO IS NULL
/*   AND PCMOVENDPEND.CODPROD = PCPEDI.CODPROD(+) 
   AND PCMOVENDPEND.NUMPED = PCPEDI.NUMPED(+) 
   AND PCMOVENDPEND.NUMOS = PCWMSERRO.NUMOS(+)*/  
   AND PCMOVENDPEND.CODFUNCOS IS NOT NULL 
   --AND PCEMPR.MATRICULA = ERROS.MATRICULA(+)
   --AND PCEMPR.MATRICULA = PRODUTIVIDADE.MATRICULA(+)   
   --VarPerfil 
   --VarUnicoPerfil
   --VarSetor
   --VarUnicoFuncSep   
 GROUP BY 
       PCEMPR.CODIGOPERFIL,    
       PCPERFILUSUARIOWMS.DESCRICAOPERFIL,                
       PCMOVENDPEND.CODFUNCOS,
       PCEMPR.NOME,
       PCEMPR.MATRICULA
)

UNION ALL
SELECT *
  FROM (
WITH ERROS --Para passar uma Ãºnica vez
  AS (SELECT E.MATERRO MATRICULA
           , COUNT(DISTINCT E.NUMOS) QT_OS_COM_ERRO
           , SUM(NVL(E.QT,0)) QT_DE_ERRO
        FROM PCWMSERRO E
           , PCEMPR EM
       WHERE  E.MATERRO = EM.MATRICULA
       AND E.NUMOS IN (SELECT M.NUMOS FROM PCMOVENDPEND M WHERE M.DTINICIOOS BETWEEN to_date('1','dd/MM/yyyy HH24:mi:ss') AND to_date('1','dd/MM/yyyy HH24:mi:ss') AND M.DTINICIOOS IS NOT NULL AND M.CODOPER NOT IN ('SA','EA')
       AND M.DTFIMSEPARACAO IS NOT NULL AND M.CODFUNCEMBALADOR = EM.MATRICULA AND M.POSICAO = 'C' AND M.NUMOS IS NOT NULL)
       AND E.MATERRO = EM.MATRICULA
       group
          BY E.MATERRO    
      )
      
   , PRODUTIVIDADE
   AS (SELECT TAB.MATRICULA
           , WMS_FORMATATEMPODIA(SUM(TAB.TEMPO)) AS TEMPO
        FROM (select (MAX(dtfimconferencia)- MIN(dtinicioconferencia)) tempo
                   , NUMOS
                   , CODFUNCEMBALADOR MATRICULA
                from pcmovendpend
               where DTINICIOOS BETWEEN to_date('1','dd/MM/yyyy HH24:mi:ss') AND to_date('1','dd/MM/yyyy HH24:mi:ss')
                 AND CODFUNCEMBALADOR IS NOT NULL
               GROUP 
                  BY NUMOS
                   , CODFUNCEMBALADOR
             ) TAB
       GROUP
          BY TAB.MATRICULA
       )       
      
SELECT 'EMBALADOR' TIPO,
       PCEMPR.MATRICULA,
       PCEMPR.CODIGOPERFIL,    
       PCPERFILUSUARIOWMS.DESCRICAOPERFIL,                
       PCMOVENDPEND.CODFUNCEMBALADOR FUNCIONARIO,
       PCEMPR.NOME,                    
       COUNT(DISTINCT TO_CHAR(PCMOVENDPEND.NUMOS,'FM0000000000') || TO_CHAR(PCMOVENDPEND.CODENDERECO,'FM0000000000')||PCMOVENDPEND.TIPOOS) QT_APANHA,
       TRUNC(SUM(PCMOVENDPEND.QT / DECODE(PCPRODUT.QTUNITCX,0,1,PCPRODUT.QTUNITCX))) QTCX,
       (SUM(PCMOVENDPEND.QT / DECODE(PCPRODUT.QTUNITCX,0,1,PCPRODUT.QTUNITCX))) - TRUNC(SUM(PCMOVENDPEND.QT / DECODE(PCPRODUT.QTUNITCX,0,1,PCPRODUT.QTUNITCX))) QTUND,       
       COUNT(DISTINCT PCMOVENDPEND.NUMOS) QUANT,
       COUNT(PCMOVENDPEND.CODPROD) + MAX((SELECT COUNT(*) FROM PCCORTEI I WHERE I. NUMPED=PCMOVENDPEND.NUMPED)) NUMAPANHA,
       SUM(PCMOVENDPEND.QT)QTR,
       ROUND(SUM(PCMOVENDPEND.QT * PCPRODUT.VOLUME), 4) VOLUME,
       SUM(PCMOVENDPEND.QT * PCPRODUT.PESOBRUTO) PESOBRUTO,
       (SUM(PCMOVENDPEND.QT)/COUNT(DISTINCT PCMOVENDPEND.NUMOS)) MQUANTPROD,
       (SUM(PCMOVENDPEND.QT * PCPRODUT.VOLUME)/COUNT(DISTINCT PCMOVENDPEND.NUMOS))MVOLUME,
       (SUM(PCMOVENDPEND.QT * PCPRODUT.PESOBRUTO)/COUNT(DISTINCT PCMOVENDPEND.NUMOS))MPESOBRUTO,                  
       COUNT(PCMOVENDPEND.CODPROD) TOTAPANHAS,          
       --COUNT(DISTINCT PCWMSERRO.NUMOS) QT_OS_COM_ERRO,       
       --SUM(NVL(PCWMSERRO.QT,0)) QT_DE_ERRO,     
      -- max(ERROS.QT_OS_COM_ERRO) QT_OS_COM_ERRO,
      -- max(ERROS.QT_DE_ERRO) QT_DE_ERRO,
      -- max(PRODUTIVIDADE.TEMPO) TEMPO_CALC  
      
       (SELECT MAX(QT_OS_COM_ERRO) FROM ERROS WHERE MATRICULA = PCEMPR.MATRICULA) QT_OS_COM_ERRO,
       (SELECT MAX(QT_DE_ERRO) FROM ERROS WHERE MATRICULA = PCEMPR.MATRICULA) QT_DE_ERRO,
       (SELECT MAX(TEMPO) FROM PRODUTIVIDADE WHERE MATRICULA = PCEMPR.MATRICULA) TEMPO_CALC 
         
/*        (SELECT COUNT(DISTINCT M.NUMOS) FROM PCWMSERRO E, PCMOVENDPEND M, PCEMPR EM WHERE
       M.NUMOS=E.NUMOS
       AND E.MATERRO = EM.MATRICULA
       AND M.CODOPER NOT IN ('SA','EA')
       AND M.DTINICIOOS IS NOT NULL
       AND M.DTFIMSEPARACAO IS NOT NULL
       AND M.DTESTORNO IS NULL
       AND M.CODOPER NOT IN ('SA','EA')
       AND M.DTINICIOOS BETWEEN to_date('1','dd/MM/yyyy HH24:mi:ss') AND to_date('1','dd/MM/yyyy HH24:mi:ss')
       AND M.NUMOS IS NOT NULL
       and em.matricula = PCEMPR.MATRICULA
       --AND M.TIPOOS IN (SELECT CODTIPOOS FROM PCAUTORIOS WHERE CODIGOPERFIL = 21 )
       AND M.POSICAO in('C','A')) QT_OS_COM_ERRO,
       
       nvl((SELECT SUM(NVL(E.QT,0)) FROM PCWMSERRO E WHERE E.NUMOS IN (
       SELECT DISTINCT M.NUMOS FROM PCMOVENDPEND M, PCEMPR EM WHERE
       M.NUMOS=E.NUMOS
       AND E.MATERRO = EM.MATRICULA
       AND M.CODOPER NOT IN ('SA','EA')
       AND M.DTINICIOOS IS NOT NULL
       AND M.DTFIMSEPARACAO IS NOT NULL
       -- AND M.DTESTORNO IS NULL
       AND M.CODOPER NOT IN ('SA','EA')
       --AND M.DTINICIOOS BETWEEN  '2'  AND '2'
       AND M.DTINICIOOS BETWEEN to_date('1','dd/MM/yyyy HH24:mi:ss') AND to_date('1','dd/MM/yyyy HH24:mi:ss')
       AND M.NUMOS IS NOT NULL
       and em.matricula = PCEMPR.MATRICULA
       --AND M.TIPOOS IN (SELECT CODTIPOOS FROM PCAUTORIOS WHERE CODIGOPERFIL = 21 )
       AND M.POSICAO  in('C','A') )),0) QT_DE_ERRO,  */
       -----CALCULAR TEMPO - EMBALADOR
     /* (SELECT WMS_FORMATATEMPODIA(SUM(TAB.TEMPO)) AS TEMPO
             FROM (select (MAX(dtfimconferencia) - MIN(dtinicioos)) tempo,
                          NUMOS, NVL(codfuncembalador, CODFUNCCONF) CODFUNCCONF
                     from pcmovendpend
                   where DTINICIOOS BETWEEN to_date('1','dd/MM/yyyy HH24:mi:ss') AND to_date('1','dd/MM/yyyy HH24:mi:ss')
                    GROUP BY NUMOS, NVL(codfuncembalador, CODFUNCCONF)) TAB WHERE CODFUNCCONF = PCEMPR.MATRICULA)  
        AS TEMPO_CALC*/
       -----CALCULAR TEMPO  
                                
  FROM PCPRODUT,
       PCMOVENDPEND, 
       PCEMPR,
       PCPERFILUSUARIOWMS--,
       /*ERROS,
       PRODUTIVIDADE,
       PCPEDI,
       PCWMSERRO*/    
 WHERE PCPRODUT.CODPROD = PCMOVENDPEND.CODPROD
   AND PCEMPR.MATRICULA = PCMOVENDPEND.CODFUNCEMBALADOR
   AND PCEMPR.CODIGOPERFIL = PCPERFILUSUARIOWMS.CODIGOPERFIL  
   AND PCMOVENDPEND.CODFILIAL = '1' 
   AND PCMOVENDPEND.DTFIMSEPARACAO IS NOT NULL
   AND PCMOVENDPEND.DTFIMCONFERENCIA IS NOT NULL
   AND PCMOVENDPEND.CODOPER NOT IN ('SA','EA')
  -- AND PCMOVENDPEND.DTFIMCONFERENCIA BETWEEN to_date('1','dd/MM/yyyy HH24:mi:ss') AND to_date('1','dd/MM/yyyy HH24:mi:ss')
   and PCMOVENDPEND.DTFIMCONFERENCIA >= to_date('1','dd/MM/yyyy HH24:mi:ss')
   and PCMOVENDPEND.DTFIMCONFERENCIA <= to_date('1','dd/MM/yyyy HH24:mi:ss')
   AND PCMOVENDPEND.NUMOS IS NOT NULL
   AND PCMOVENDPEND.POSICAO = 'C'
   AND PCMOVENDPEND.DTFIMOS IS NOT NULL
   AND PCMOVENDPEND.DTESTORNO IS NULL
/*   AND PCMOVENDPEND.CODPROD = PCPEDI.CODPROD(+) 
   AND PCMOVENDPEND.NUMPED = PCPEDI.NUMPED(+) 
   AND PCMOVENDPEND.NUMOS = PCWMSERRO.NUMOS(+)  */
   AND PCMOVENDPEND.CODFUNCEMBALADOR IS NOT NULL 
   --AND PCEMPR.MATRICULA = ERROS.MATRICULA(+)
   --AND PCEMPR.MATRICULA = PRODUTIVIDADE.MATRICULA(+)   
   --VarPerfil 
   --VarUnicoPerfil
   --VarSetor
   --VarUnicoFuncEmb
 GROUP BY 
       PCEMPR.CODIGOPERFIL,    
       PCPERFILUSUARIOWMS.DESCRICAOPERFIL,                
       PCMOVENDPEND.CODFUNCEMBALADOR,
       PCEMPR.NOME,
       PCEMPR.MATRICULA
)                

UNION ALL
SELECT *
  FROM (
WITH ERROS --Para passar uma Ãºnica vez
  AS ( SELECT E.MATERRO MATRICULA
           , COUNT(DISTINCT E.NUMOS) QT_OS_COM_ERRO
           , SUM(NVL(E.QT,0)) QT_DE_ERRO
        FROM PCWMSERRO E
           , PCEMPR EM
       WHERE  E.MATERRO = EM.MATRICULA
       AND E.NUMOS IN (SELECT M.NUMOS 
                         FROM PCMOVENDPEND M 
                        WHERE M.DTINICIOOS BETWEEN to_date('1','dd/MM/yyyy HH24:mi:ss') AND to_date('1','dd/MM/yyyy HH24:mi:ss') 
                          AND M.DTINICIOOS IS NOT NULL 
                          AND M.CODOPER NOT IN ('SA','EA')
                          AND M.DTFIMSEPARACAO IS NOT NULL 
                          AND NVL(M.CODFUNCCOFERENTE,M.CODFUNCCONF)  = EM.MATRICULA 
                          AND M.POSICAO = 'C'
                          AND M.NUMOS IS NOT NULL)
       group
          BY E.MATERRO    
      )
      
   , PRODUTIVIDADE
   AS (SELECT TAB.MATRICULA
           , WMS_FORMATATEMPODIA(SUM(TAB.TEMPO)) AS TEMPO
        FROM (select (MAX(PCMOVENDPEND.dtfimconferencia)- MIN(PCMOVENDPEND.dtinicioconferencia)) tempo
                   , PCMOVENDPEND.NUMOS
                   , NVL(PCMOVENDPEND.CODFUNCCOFERENTE, PCMOVENDPEND.CODFUNCCONF) MATRICULA
                from pcmovendpend
               where PCMOVENDPEND.DTINICIOOS BETWEEN to_date('1','dd/MM/yyyy HH24:mi:ss') AND to_date('1','dd/MM/yyyy HH24:mi:ss')
                 AND (PCMOVENDPEND.CODFUNCCOFERENTE IS NOT NULL OR PCMOVENDPEND.CODFUNCCONF IS NOT NULL ) 
               GROUP 
                  BY PCMOVENDPEND.NUMOS
                   , NVL(PCMOVENDPEND.CODFUNCCOFERENTE, PCMOVENDPEND.CODFUNCCONF)
             ) TAB
       GROUP
          BY TAB.MATRICULA
       )       
             
SELECT 'CONFERENTE' TIPO,
       PCEMPR.CODIGOPERFIL,  
       PCEMPR.MATRICULA,   
       PCPERFILUSUARIOWMS.DESCRICAOPERFIL,                
       NVL(PCMOVENDPEND.CODFUNCCOFERENTE, PCMOVENDPEND.CODFUNCCONF) FUNCIONARIO,
       PCEMPR.NOME,                    
       COUNT(DISTINCT TO_CHAR(PCMOVENDPEND.NUMOS,'FM0000000000') || TO_CHAR(PCMOVENDPEND.CODENDERECO,'FM0000000000')||PCMOVENDPEND.TIPOOS) QT_APANHA,
       TRUNC(SUM(PCMOVENDPEND.QT / DECODE(PCPRODUT.QTUNITCX,0,1,PCPRODUT.QTUNITCX))) QTCX,
       (SUM(PCMOVENDPEND.QT / DECODE(PCPRODUT.QTUNITCX,0,1,PCPRODUT.QTUNITCX))) - TRUNC(SUM(PCMOVENDPEND.QT / DECODE(PCPRODUT.QTUNITCX,0,1,PCPRODUT.QTUNITCX))) QTUND,       
       COUNT(DISTINCT PCMOVENDPEND.NUMOS) QUANT,
       COUNT(PCMOVENDPEND.CODPROD) + MAX((SELECT COUNT(*) FROM PCCORTEI I WHERE I. NUMPED=PCMOVENDPEND.NUMPED)) NUMAPANHA,
       SUM(PCMOVENDPEND.QT)QTR,
       ROUND(SUM(PCMOVENDPEND.QT * PCPRODUT.VOLUME), 4) VOLUME,
       SUM(PCMOVENDPEND.QT * PCPRODUT.PESOBRUTO) PESOBRUTO,
       (SUM(PCMOVENDPEND.QT)/COUNT(DISTINCT PCMOVENDPEND.NUMOS)) MQUANTPROD,
       (SUM(PCMOVENDPEND.QT * PCPRODUT.VOLUME)/COUNT(DISTINCT PCMOVENDPEND.NUMOS))MVOLUME,
       (SUM(PCMOVENDPEND.QT * PCPRODUT.PESOBRUTO)/COUNT(DISTINCT PCMOVENDPEND.NUMOS))MPESOBRUTO,                  
       COUNT(PCMOVENDPEND.CODPROD) TOTAPANHAS,          
       --COUNT(DISTINCT PCWMSERRO.NUMOS) QT_OS_COM_ERRO,       
       --SUM(NVL(PCWMSERRO.QT,0)) QT_DE_ERRO, 
       --max(ERROS.QT_OS_COM_ERRO) QT_OS_COM_ERRO,
       --max(ERROS.QT_DE_ERRO) QT_DE_ERRO,
       --max(PRODUTIVIDADE.TEMPO) TEMPO_CALC 
       
       (SELECT MAX(QT_OS_COM_ERRO) FROM ERROS WHERE MATRICULA = PCEMPR.MATRICULA) QT_OS_COM_ERRO,
       (SELECT MAX(QT_DE_ERRO) FROM ERROS WHERE MATRICULA = PCEMPR.MATRICULA) QT_DE_ERRO,
       (SELECT MAX(TEMPO) FROM PRODUTIVIDADE WHERE MATRICULA = PCEMPR.MATRICULA) TEMPO_CALC  
       
/*      (SELECT COUNT(DISTINCT M.NUMOS) FROM PCWMSERRO E, PCMOVENDPEND M, PCEMPR EM WHERE
       M.NUMOS=E.NUMOS
       AND E.MATERRO = EM.MATRICULA
       AND M.CODOPER NOT IN ('SA','EA')
       AND M.DTINICIOOS IS NOT NULL
       AND M.DTFIMSEPARACAO IS NOT NULL
       AND M.DTESTORNO IS NULL
       AND M.CODOPER NOT IN ('SA','EA')
       AND M.DTINICIOOS BETWEEN to_date('1','dd/MM/yyyy HH24:mi:ss') AND to_date('1','dd/MM/yyyy HH24:mi:ss')
       AND M.NUMOS IS NOT NULL
       and em.matricula = PCEMPR.MATRICULA
       AND M.POSICAO in('C','A')) QT_OS_COM_ERRO,
       
  nvl((SELECT SUM(NVL(E.QT,0)) FROM PCWMSERRO E WHERE E.NUMOS IN (
       SELECT DISTINCT M.NUMOS FROM PCMOVENDPEND M, PCEMPR EM WHERE
       M.NUMOS=E.NUMOS
       AND E.MATERRO = EM.MATRICULA
       AND M.CODOPER NOT IN ('SA','EA')
       AND M.DTINICIOOS IS NOT NULL
       AND M.DTFIMSEPARACAO IS NOT NULL
       -- AND M.DTESTORNO IS NULL
       AND M.CODOPER NOT IN ('SA','EA')
       --AND M.DTINICIOOS BETWEEN  '2'  AND '2'
       AND M.DTINICIOOS BETWEEN to_date('1','dd/MM/yyyy HH24:mi:ss') AND to_date('1','dd/MM/yyyy HH24:mi:ss')
       AND M.NUMOS IS NOT NULL
       and em.matricula = PCEMPR.MATRICULA
       AND M.POSICAO  in('C','A') )),0) QT_DE_ERRO,      */
       ---WMS_FORMATATEMPODIA(SUM(DTFIMCONFERENCIA-DTINICIOCONFERENCIA)) TEMPO_CALC              
 -----CALCULAR TEMPO - CONFERENTE
 /*
      (SELECT WMS_FORMATATEMPODIA(SUM(TAB.TEMPO)) AS TEMPO
             FROM (select (MAX(dtfimconferencia)- MIN(dtinicioconferencia)) tempo,
                          NUMOS, NVL(CODFUNCCOFERENTE, CODFUNCCONF) CODFUNCCONF
                     from pcmovendpend
                   where DTINICIOOS BETWEEN to_date('1','dd/MM/yyyy HH24:mi:ss') AND to_date('1','dd/MM/yyyy HH24:mi:ss')
                   GROUP BY NUMOS, NVL(CODFUNCCOFERENTE, CODFUNCCONF)) TAB WHERE CODFUNCCONF = PCEMPR.MATRICULA)  
        AS TEMPO_CALC*/
        
       -----CALCULAR TEMPO  
  FROM PCPRODUT,
       PCMOVENDPEND, 
       PCEMPR,
       PCPERFILUSUARIOWMS--,
       /*ERROS,
       PRODUTIVIDADE
       PCPEDI,
       PCWMSERRO*/    
 WHERE PCPRODUT.CODPROD = PCMOVENDPEND.CODPROD
   AND PCEMPR.MATRICULA = NVL(PCMOVENDPEND.CODFUNCCOFERENTE,PCMOVENDPEND.CODFUNCCONF )
   AND PCEMPR.CODIGOPERFIL = PCPERFILUSUARIOWMS.CODIGOPERFIL  
   AND PCMOVENDPEND.CODFILIAL = '1' 
   AND PCMOVENDPEND.DTFIMSEPARACAO IS NOT NULL
   AND PCMOVENDPEND.DTFIMCONFERENCIA IS NOT NULL
   AND PCMOVENDPEND.DTINICIOCONFERENCIA IS NOT NULL
   AND PCMOVENDPEND.CODOPER NOT IN ('SA','EA')
   --AND PCMOVENDPEND.DTINICIOCONFERENCIA BETWEEN to_date('1','dd/MM/yyyy HH24:mi:ss') AND to_date('1','dd/MM/yyyy HH24:mi:ss')
   and PCMOVENDPEND.DTINICIOCONFERENCIA >= to_date('1','dd/MM/yyyy HH24:mi:ss')
   and PCMOVENDPEND.DTINICIOCONFERENCIA <= to_date('1','dd/MM/yyyy HH24:mi:ss')
   AND PCMOVENDPEND.NUMOS IS NOT NULL
   AND PCMOVENDPEND.POSICAO = 'C'
   AND PCMOVENDPEND.DTFIMOS IS NOT NULL
   AND PCMOVENDPEND.DTESTORNO IS NULL
   --AND PCEMPR.MATRICULA = ERROS.MATRICULA(+)
   --AND PCEMPR.MATRICULA = PRODUTIVIDADE.MATRICULA(+)   
/*   AND PCMOVENDPEND.CODPROD = PCPEDI.CODPROD(+) 
   AND PCMOVENDPEND.NUMPED = PCPEDI.NUMPED(+) 
   AND PCMOVENDPEND.NUMOS = PCWMSERRO.NUMOS(+)  
   AND PCWMSERRO.MATERRO(+) = NVL(PCMOVENDPEND.CODFUNCCOFERENTE,PCMOVENDPEND.CODFUNCCONF)*/
   AND (PCMOVENDPEND.CODFUNCCOFERENTE IS NOT NULL OR PCMOVENDPEND.CODFUNCCONF IS NOT NULL ) 
   --VarPerfil 
   --VarUnicoPerfil
   --VarSetor  
   --VarUnicoFuncConf
 GROUP BY 
       PCEMPR.CODIGOPERFIL,    
       PCPERFILUSUARIOWMS.DESCRICAOPERFIL,                
       PCMOVENDPEND.CODFUNCCOFERENTE, 
       PCMOVENDPEND.CODFUNCCONF,
       PCEMPR.NOME,
       PCEMPR.MATRICULA
) 