SELECT TRUNC(M.DATA) DATA,
       M.CODFILIAL,
       M.NUMOS,
       WMS_GETBOX(M.NUMOS, 'C') NUMBOX,
       WMS_CONCAT(DISTINCT M.NUMPALETE) PALETES,
    MAX(CLI.CLIENTES) CLIENTES,
       WMS_GETBOX(M.NUMOS, 'D') DESCRICAOBOX,
       MIN((SELECT MIN(E.DEPOSITO)
             FROM PCENDERECO   E
            WHERE E.CODENDERECO = M.CODENDERECO
          )) MENOR_DEPOSITO,
       (SELECT T.CODIGO || ' - ' || UPPER(T.DESCRICAO)
          FROM PCTIPOOS T
         WHERE T.CODIGO = M.TIPOOS) TIPOOS,
 FLOOR(ROUND (CASE
               WHEN (NVL((SELECT SUM(QTSEPARADA) FROM PCMOVENDPEND WHERE NUMOS = M.NUMOS), 0)) = 0 THEN
                 0
               ELSE
                 (NVL((SELECT SUM(QTSEPARADA) FROM PCMOVENDPEND WHERE NUMOS = M.NUMOS), 0)) / (NVL((SELECT SUM(QT) FROM PCMOVENDPEND WHERE NUMOS = M.NUMOS), 0)) * 100
             END, 2)) PERCSEPARADA,
 FLOOR(ROUND (CASE
               WHEN (NVL((SELECT SUM(QTCONFERIDA) FROM PCMOVENDPEND WHERE NUMOS = M.NUMOS), 0)) = 0 THEN
                 0
               ELSE
                 (NVL((SELECT SUM(QTCONFERIDA) FROM PCMOVENDPEND WHERE NUMOS = M.NUMOS), 0)) / (NVL((SELECT SUM(QT) FROM PCMOVENDPEND WHERE NUMOS = M.NUMOS), 0)) * 100
             END, 2)) PERCCONFERIDA,
(SELECT COUNT(DISTINCT CODPROD) FROM PCMOVENDPEND WHERE NUMOS = M.NUMOS) AS QTDEITENS,
       MIN(M.DTINICIOOS) DTINICIOOS,
       TRUNC(M.DATALIBERACAO) DATALIBERACAO,
       MIN((SELECT MIN(E.RUA)
             FROM PCENDERECO   E
            WHERE E.CODENDERECO = M.CODENDERECO
          )) RUA,
       MAX((SELECT E.MATRICULA || ' - ' || E.NOME
          FROM PCEMPR E
         WHERE E.MATRICULA = M.CODFUNCOS)) FUNCIONARIO,
       M.PRIORIDADERF,
       (CASE
         WHEN NVL(M.NUMCAR, 0) = 0 AND
           (SELECT COUNT(DISTINCT O.NUMPED)
              FROM PCMOVENDPEND O
             WHERE O.NUMOS = M.NUMOS) = 0
               AND NVL(M.NUMTRANSVENDA, 0) > 0 THEN
           'TRANS.VENDA - ' || M.NUMTRANSVENDA
         WHEN NVL(M.NUMCAR, 0) = 0 AND
           (SELECT COUNT(DISTINCT O.NUMPED)
              FROM PCMOVENDPEND O
             WHERE O.NUMOS = M.NUMOS) = 0
               AND NVL(M.NUMTRANSVENDA, 0) = 0
               AND M.TIPOOS IN (51, 52, 60, 96, 97, 98) THEN
           'BÔNUS - '||M.NUMBONUS
         WHEN NVL(M.NUMCAR, 0) = 0 AND
           (SELECT COUNT(DISTINCT O.NUMPED)
              FROM PCMOVENDPEND O
             WHERE O.NUMOS = M.NUMOS) = 0
               AND NVL(M.NUMTRANSVENDA, 0) = 0
               AND M.TIPOOS IN (50, 53, 54, 56, 57, 58, 61) THEN
           'TRANSF/ABAST'
         WHEN NVL(M.NUMCAR, 0) = 0 AND
           (SELECT COUNT(DISTINCT O.NUMPED)
              FROM PCMOVENDPEND O
             WHERE O.NUMOS = M.NUMOS) =1 THEN
           'PEDIDO - ' || (SELECT MAX(DISTINCT O.NUMPED)
                               FROM PCMOVENDPEND O
                              WHERE O.NUMOS = M.NUMOS)
         WHEN NVL(M.NUMCAR, 0) > 0 AND
           (SELECT COUNT(DISTINCT O.NUMPED)
              FROM PCMOVENDPEND O
             WHERE O.NUMOS = M.NUMOS) >= 0 THEN
           'CARGA - ' || M.NUMCAR
       END) MOVIMENTACAO,
      NVL(M.NUMTRANSVENDA, 0) NUMTRANSVENDA,
      (CASE
         WHEN M.TIPOOS IN (13, 20, 22, 17 ,18) AND NVL(M.NUMCAR, 0) > 0 THEN
           MAX(TO_CHAR(M.NUMPED))
         ELSE
           '-'
        END) PEDIDOS,
       (SELECT TO_CHAR(PCROTAEXP.CODROTA) || ' - ' || PCROTAEXP.DESCRICAO
          FROM PCROTAEXP,
               PCCARREG
         WHERE PCCARREG.CODROTAPRINC = PCROTAEXP.CODROTA
           AND PCCARREG.NUMCAR = M.NUMCAR
           AND PCCARREG.CODROTAPRINC IS NOT NULL) ROTA,
       M.NUMTRANSWMS,
       M.NUMBONUS,
       MIN(M.SEQUMA) SEQUMA,
       DECODE(TRUNC(M.DATALIBERACAO), NULL, 'NAO', 'SIM') OSLIBERADA,
       MIN(NVL(M.NUMSEQMONTAGEM,0)) SEQMONTAGEM,
       CALCULAHORAS(MIN(M.DTINICIOOS), MAX(NVL(M.DTFIMSEPARACAO, M.DTFIMOS))) TEMPOSEP,
       ROUND(CASE
               WHEN SUM(NVL(M.QTCONFERIDA, 0)) = 0 THEN
                 0
               ELSE
                 SUM(NVL(M.QTCONFERIDA, 0)) / SUM(NVL(M.QT, 0)) * 100
             END, 0) PERCCONFERIDA,
       CALCULAHORAS(MIN(M.DTINICIOCONFERENCIA), MAX(NVL(M.DTFIMCONFERENCIA, M.DTFIMOS))) TEMPOCONF,
       (SELECT E.MATRICULA || ' - ' || E.NOME
          FROM PCEMPR E
         WHERE E.MATRICULA = (SELECT MAX(P.CODFUNCCONF)
                                FROM PCMOVENDPEND P
                               WHERE P.NUMOS = M.NUMOS)) CONFERENTE,
       NVL(M.LIBERADOVOCOLLECT,'N') LIBERADOVOCOLLECT,
       M.NUMAGRUPADOR,
       M.NUMVOLAGRUPADOR
  FROM PCMOVENDPEND M
,(SELECT WMS_CONCAT(DISTINCT PCCLIENT.CODCLI||'-'||PCCLIENT.CLIENTE ||' ') CLIENTES, PCMOVENDPEND.NUMOS
    FROM PCCLIENT , PCPEDC , PCMOVENDPEND
   WHERE PCCLIENT.CODCLI = PCPEDC.CODCLI
     AND PCMOVENDPEND.NUMPED = PCPEDC.NUMPED
   GROUP BY PCMOVENDPEND.NUMOS) CLI
 WHERE M.CODFILIAL IN ('1')
   AND M.NUMOS = CLI.NUMOS(+)
   AND M.DTESTORNO IS NULL
   AND M.DATA BETWEEN TO_DATE('01/08/2026', 'DD/MM/YYYY') AND TO_DATE('31/08/2026', 'DD/MM/YYYY')
   AND M.POSICAO <> 'C'
   AND M.TIPOOS IN (9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,21, 22, 23, 41)
   AND M.POSICAO = 'P'
 GROUP BY M.DATA,
          M.NUMOS,
          M.CODFILIAL,
          M.TIPOOS,
          M.PRIORIDADERF,
          M.NUMBONUS,
          M.NUMTRANSWMS,
          M.NUMTRANSVENDA,
          M.NUMCAR,
          TRUNC(M.DATALIBERACAO),
          M.LIBERADOVOCOLLECT,
          M.NUMAGRUPADOR,
          M.NUMVOLAGRUPADOR
 ORDER BY M.PRIORIDADERF
